name: "lc-tool"
description: "automatic sync leetcode status"
inputs:
  leetcode_username:
    description: "leetcode username"
    required: true
  leetcode_password:
    description: "leetcode password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download lc-tool
      shell: bash
    - id: fetch-status
      name: Run LC Tool generate report
      shell: bash